version: "3.9"
   
services:
  app:
    container_name: app
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - ALLOWED_HOSTS=*